### PR TITLE
Create basic README.md with CF link, optimize textures.

### PR DESCRIPTION
**Pull request by RDKRACZ**

### CODE REVIEW

**Comment by CammiePone** [comment]
so... how exactly did you optimise the assets?

**Comment by RDKRACZ** [comment]
Forgot about the description, sorry.
I used oxipng for this `oxipng -o max -s full -r --fix -t 8 -Z` - https://github.com/shssoichiro/oxipng

>I guess the better question is why?

Well, the jar will be smaller (also more devs would know about optimizing the assets) and I wanted to add a download link to the readme but doing pr for just this would be...

This does not reduce the quality of the files, only the size. You can use this Github bot http://imgbot.net to achieve similar results to mine (tbh the results are worse but the bot does not require any knowledge or manual to use, it just opens ready-to-merge prs).

**Comment by CammiePone** [comment]
okay but, like, the difference in jar size would be so minuscule that it wouldn't even show up on CurseForge and no one would even know it happened. This is the kinda thing better suited to a large mod, like Bewitchment

**Comment by RDKRACZ** [comment]
>This is the kinda thing better suited to a large mod, like Bewitchment

Already done, waiting to be pr'ed :)

>the difference in jar size would be so minuscule that it wouldn't even show up on CurseForge and no one would even know it happened

Well, nobody needs to know, this is just a minor change so it can wait until you have something bigger to update.

**Comment by CammiePone** [comment]
I'm gonna go with thank you for the effort, but I don't really think it's worth merging. I will eventually get around to making a proper readme. Eventually.

**Pull request closed without merging**
